---
title: "Install NVIDIA driver on your ubuntu"
description: |
  Install the official NVIDIA driver using a third-party library and disable the open-source driver. 
author: "Guofeng Lin"
date: "2023-11-30"
categories: [Linux, Ubuntu]
sidebar: false
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
---

## 1. add third-party repositpry PPA

```bash
sudo add-apt-repository ppa:graphics-drivers/ppa
sudo apt update
```

## 2. disable the open-source driver nouveau

Ubuntu uses the open-source driver nouveau by default, so you need to disable nouveau before installing the NVIDIA driver.

```bash
sudo bash -c "echo blacklist nouveau > /etc/modprobe.d/blacklist-nvidia-nouveau.conf"
sudo bash -c "echo options nouveau modeset=0 >> /etc/modprobe.d/blacklist-nvidia-nouveau.conf"
```

Then you can enter the following command to verify that the above command was entered into the file "/etc/modprobe.d/blacklist-nvidia-nouveau.conf".

```bash
cat /etc/modprobe.d/blacklist-nvidia-nouveau.conf
```

It works if the following message is displayed：

```bash
$ cat /etc/modprobe.d/blacklist-nvidia-nouveau.conf
blacklist nouveau
options nouveau modeset=0
```

## 3. Install the official NVIDIA driver

Uninstall the old NVIDIA driver (if needed):

```bash
sudo apt-get purge nvidia*
```

Add drivers to PPA repository:

```bash
sudo add-apt-repository ppa:graphics-drivers
sudo apt-get update
```

Search for latest NVIDIA drivers:

```bash
sudo apt-cache search nvidia
```

Search for recommanded NVIDIA drivers:

```bash
ubuntu-drivers devices
```

Open "Ubuntu Software" in your system, then click "Software & Updates" in the upper left corner, then click "Additional Drivers," select one of the drivers (I find it best to choose a newer, proprietary driver), and then click "Apply Changes." After installation, the system will ask you to restart. If the screen looks great after restarting, you're all done!

View the current driver:

```bash
nvidia-smi
```