---
title: "What is dconf-editor"
description: |
  use dconf-editor to make your ubuntu destop more friendly. 
author: "Guofeng Lin"
date: "2020-10-22"
categories: [Linux, Ubuntu]
sidebar: false
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
---

dconf-editor is a very simple and easy-to-use Ubuntu settings editing program that visualizes a large number of Ubuntu system settings.

The benefits are obvious: you no longer need to search for commands on Google and then manually type them in, worrying about whether the commands are correct.

## 1. Installation

```bash
$ sudo apt install dconf-editor
```

## 2. How to use dconf-editor

Once installed, it's very easy to open: press ALT+F2 to open the command search box, and enter dconf-editor.

**use case 1** 

If you've been using Mac or Windows for a long time, you might find the Ubuntu 18.04 desktop a bit unfamiliar. For example, the "Show Applications" button in the dock is located at the very end of the dock by default. This means that especially when the dock is placed at the bottom, you can only find this distant "Show Applications" button in the lower right corner of the screen. So how do you change it?

* Step 1: press ALT+F2 to open dconf-editor
* Step 2: locate the `show-apps-at-top` option in the following path `> org > gnome > shell > extension > dash-to-dock`
* Step 3: set `show-apps-at-top` to `on`

